api_platform:
    title: 'Wapp API'
    description: 'The API of an Ionic mobile application named WhereU'
    version: '1.0.0'

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
